services:
  database:
    image: mysql/mysql-server:8.0
    container_name: translate_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: translate_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    command:
      --default-authentication-plugin=mysql_native_password 
      --bind-address=0.0.0.0
      --default-time-zone=America/Sao_Paulo
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  
volumes:
  mysql_data: